from unittest.mock import Mock

import pytest

from merit_api import MeritAPI


READ_METHOD_CASES = [
    (
        "customers.get_list",
        "_post",
        lambda client: client.customers.get_list(Name="Acme"),
        ("getcustomers", {"Name": "Acme"}),
        {},
    ),
    (
        "customers.get_groups",
        "_post",
        lambda client: client.customers.get_groups(),
        ("getcustomergroups", {}),
        {"version": "v2"},
    ),
    (
        "vendors.get_list",
        "_post",
        lambda client: client.vendors.get_list(RegNo="123"),
        ("getvendors", {"RegNo": "123"}),
        {},
    ),
    (
        "vendors.get_groups",
        "_post",
        lambda client: client.vendors.get_groups(),
        ("getvendorgroups", {}),
        {"version": "v2"},
    ),
    (
        "items.get_list",
        "_post",
        lambda client: client.items.get_list(Code="ITEM-1"),
        ("getitems", {"Code": "ITEM-1"}),
        {},
    ),
    (
        "items.get_groups",
        "_post",
        lambda client: client.items.get_groups(),
        ("getitemgroups", {}),
        {"version": "v2"},
    ),
    (
        "sales.get_invoices",
        "_post",
        lambda client: client.sales.get_invoices(PeriodStart="20260101", PeriodEnd="20260131"),
        ("getinvoices", {"PeriodStart": "20260101", "PeriodEnd": "20260131"}),
        {"version": "v2"},
    ),
    (
        "sales.get_invoice",
        "_post",
        lambda client: client.sales.get_invoice("inv-id", add_attachment=True),
        ("getinvoice", {"Id": "inv-id", "AddAttachment": True}),
        {},
    ),
    (
        "sales.get_offers",
        "_post",
        lambda client: client.sales.get_offers(PeriodStart="20260101", PeriodEnd="20260131", DateType=0, UnPaid=False),
        ("getoffers", {"PeriodStart": "20260101", "PeriodEnd": "20260131", "DateType": 0, "UnPaid": False}),
        {"version": "v2"},
    ),
    (
        "sales.get_offer",
        "_post",
        lambda client: client.sales.get_offer("offer-id"),
        ("getoffer", {"Id": "offer-id"}),
        {"version": "v2"},
    ),
    (
        "sales.get_recurring_invoices",
        "_post",
        lambda client: client.sales.get_recurring_invoices(PeriodStart="20260101", PeriodEnd="20260131", DateType=0),
        ("getperinvoices", {"PeriodStart": "20260101", "PeriodEnd": "20260131", "DateType": 0}),
        {"version": "v2"},
    ),
    (
        "sales.get_recurring_invoice",
        "_post",
        lambda client: client.sales.get_recurring_invoice("rec-id"),
        ("getperinvoice", {"Id": "rec-id"}),
        {"version": "v2"},
    ),
    (
        "sales.get_recurring_invoice_addresses",
        "_post",
        lambda client: client.sales.get_recurring_invoice_addresses(CustomerId="cust-id"),
        ("getpershaddress", {"CustomerId": "cust-id"}),
        {"version": "v2"},
    ),
    (
        "purchases.get_invoices",
        "_post",
        lambda client: client.purchases.get_invoices(PeriodStart="20260101", PeriodEnd="20260131"),
        ("getpurchorders", {"PeriodStart": "20260101", "PeriodEnd": "20260131"}),
        {},
    ),
    (
        "purchases.get_invoice",
        "_post",
        lambda client: client.purchases.get_invoice("bill-id", skip_attachment=False),
        ("getpurchorder", {"Id": "bill-id", "SkipAttachment": False}),
        {},
    ),
    (
        "purchases.get_orders",
        "_post",
        lambda client: client.purchases.get_orders(PeriodStart="20260101", PeriodEnd="20260131"),
        ("GetPOrders", {"PeriodStart": "20260101", "PeriodEnd": "20260131"}),
        {"version": "v2"},
    ),
    (
        "financial.get_payments",
        "_post",
        lambda client: client.financial.get_payments(PeriodStart="20260101", PeriodEnd="20260131"),
        ("getpayments", {"PeriodStart": "20260101", "PeriodEnd": "20260131"}),
        {},
    ),
    (
        "financial.get_payment_types",
        "_post",
        lambda client: client.financial.get_payment_types(),
        ("getpaymenttypes", {}),
        {"version": "v2"},
    ),
    (
        "financial.get_payment_imports",
        "_get",
        lambda client: client.financial.get_payment_imports(bankId="bank-id", bookingDateFrom="2026-01-01", bookingDateTo="2026-01-31"),
        ("PaymentImports", {"bankId": "bank-id", "bookingDateFrom": "2026-01-01", "bookingDateTo": "2026-01-31"}),
        {"version": "v2"},
    ),
    (
        "financial.get_expense_payments",
        "_get",
        lambda client: client.financial.get_expense_payments("bank-id", docDateFrom="2026-01-01", docDateTo="2026-01-31"),
        ("Banks/bank-id/ExpensePayments", {"docDateFrom": "2026-01-01", "docDateTo": "2026-01-31"}),
        {"version": "v2"},
    ),
    (
        "financial.get_income_payments",
        "_get",
        lambda client: client.financial.get_income_payments("bank-id", docDateFrom="2026-01-01", docDateTo="2026-01-31"),
        ("Banks/bank-id/IncomePayments", {"docDateFrom": "2026-01-01", "docDateTo": "2026-01-31"}),
        {"version": "v2"},
    ),
    (
        "financial.get_gl_batches",
        "_post",
        lambda client: client.financial.get_gl_batches(PeriodStart="20260101", PeriodEnd="20260131"),
        ("getglbatches", {"PeriodStart": "20260101", "PeriodEnd": "20260131"}),
        {},
    ),
    (
        "financial.get_gl_batch",
        "_post",
        lambda client: client.financial.get_gl_batch("batch-id"),
        ("getglbatch", {"Id": "batch-id"}),
        {},
    ),
    (
        "financial.get_gl_batches_full",
        "_post",
        lambda client: client.financial.get_gl_batches_full(PeriodStart="20260101", PeriodEnd="20260131"),
        ("GetGLBatchesFull", {"PeriodStart": "20260101", "PeriodEnd": "20260131"}),
        {},
    ),
    (
        "financial.get_banks",
        "_post",
        lambda client: client.financial.get_banks(),
        ("getbanks",),
        {},
    ),
    (
        "financial.get_accounts",
        "_post",
        lambda client: client.financial.get_accounts(),
        ("getaccounts", {}),
        {},
    ),
    (
        "financial.get_costs",
        "_post",
        lambda client: client.financial.get_costs(),
        ("getcostcenters",),
        {},
    ),
    (
        "financial.get_projects",
        "_post",
        lambda client: client.financial.get_projects(),
        ("getprojects",),
        {},
    ),
    (
        "financial.get_departments",
        "_post",
        lambda client: client.financial.get_departments(),
        ("getdepartments", {}),
        {},
    ),
    (
        "financial.get_financial_years",
        "_post",
        lambda client: client.financial.get_financial_years(),
        ("getaccperiods", {}),
        {"version": "v2"},
    ),
    (
        "inventory.get_locations",
        "_post",
        lambda client: client.inventory.get_locations(),
        ("getlocations", {}),
        {"version": "v2"},
    ),
    (
        "inventory.get_movements",
        "_post",
        lambda client: client.inventory.get_movements(PeriodStart="20260101", PeriodEnd="20260131"),
        ("getinvmovements", {"PeriodStart": "20260101", "PeriodEnd": "20260131"}),
        {"version": "v2"},
    ),
    (
        "assets.get_locations",
        "_post",
        lambda client: client.assets.get_locations(),
        ("getfalocations", {}),
        {"version": "v2"},
    ),
    (
        "assets.get_responsible_persons",
        "_post",
        lambda client: client.assets.get_responsible_persons(),
        ("getfaresppersons", {}),
        {"version": "v2"},
    ),
    (
        "assets.get_fixed_assets",
        "_post",
        lambda client: client.assets.get_fixed_assets(PeriodStart="20260101", PeriodEnd="20260131"),
        ("getfixassets", {"PeriodStart": "20260101", "PeriodEnd": "20260131"}),
        {"version": "v2"},
    ),
    (
        "taxes.get_list",
        "_post",
        lambda client: client.taxes.get_list(),
        ("gettaxes",),
        {},
    ),
    (
        "dimensions.get_list",
        "_post",
        lambda client: client.dimensions.get_list(),
        ("getdimensions", {"AllValues": False}),
        {"version": "v2"},
    ),
    (
        "pricing.get_prices",
        "_post",
        lambda client: client.pricing.get_prices(ItemCode="ITEM-1"),
        ("getprices", {"ItemCode": "ITEM-1"}),
        {"version": "v2"},
    ),
    (
        "pricing.get_discounts",
        "_post",
        lambda client: client.pricing.get_discounts(CustomerId="cust-id"),
        ("getdiscounts", {"CustomerId": "cust-id"}),
        {"version": "v2"},
    ),
    (
        "pricing.get_price",
        "_post",
        lambda client: client.pricing.get_price(ItemCode="ITEM-1", CustomerId="cust-id"),
        ("getprice", {"ItemCode": "ITEM-1", "CustomerId": "cust-id"}),
        {"version": "v2"},
    ),
    (
        "reports.get_customer_debts",
        "_post",
        lambda client: client.reports.get_customer_debts(PeriodStart="20260101", PeriodEnd="20260131"),
        ("getcustdebtrep", {"PeriodStart": "20260101", "PeriodEnd": "20260131"}),
        {},
    ),
    (
        "reports.get_customer_payments",
        "_post",
        lambda client: client.reports.get_customer_payments(PeriodStart="20260101", PeriodEnd="20260131"),
        ("getcustpaymrep", {"PeriodStart": "20260101", "PeriodEnd": "20260131"}),
        {"version": "v2"},
    ),
    (
        "reports.get_more_data",
        "_post",
        lambda client: client.reports.get_more_data(Token="next-token"),
        ("getmoredata", {"Token": "next-token"}),
        {"version": "v2"},
    ),
    (
        "reports.get_profit",
        "_post",
        lambda client: client.reports.get_profit(PeriodStart="20260101", PeriodEnd="20260131"),
        ("getprofitrep", {"PeriodStart": "20260101", "PeriodEnd": "20260131"}),
        {},
    ),
    (
        "reports.get_balance",
        "_post",
        lambda client: client.reports.get_balance(PeriodStart="20260101", PeriodEnd="20260131"),
        ("getbalancerep", {"PeriodStart": "20260101", "PeriodEnd": "20260131"}),
        {},
    ),
    (
        "reports.get_inventory",
        "_post",
        lambda client: client.reports.get_inventory(PeriodStart="20260101", PeriodEnd="20260131"),
        ("getinventoryreport", {"PeriodStart": "20260101", "PeriodEnd": "20260131"}),
        {"version": "v2"},
    ),
    (
        "reports.get_sales",
        "_post",
        lambda client: client.reports.get_sales(PeriodStart="20260101", PeriodEnd="20260131"),
        ("getsalesrep", {"PeriodStart": "20260101", "PeriodEnd": "20260131"}),
        {"version": "v2"},
    ),
    (
        "reports.get_purchases",
        "_post",
        lambda client: client.reports.get_purchases(PeriodStart="20260101", PeriodEnd="20260131"),
        ("getpurchrep", {"PeriodStart": "20260101", "PeriodEnd": "20260131"}),
        {"version": "v2"},
    ),
    (
        "reference.get_units",
        "_post",
        lambda client: client.reference.get_units(),
        ("getunits", {}),
        {},
    ),
]


@pytest.mark.parametrize("_name,mock_attr,invoke,expected_args,expected_kwargs", READ_METHOD_CASES)
def test_read_methods_delegate_to_expected_endpoints(_name, mock_attr, invoke, expected_args, expected_kwargs):
    client = MeritAPI("test_id", "test_key")
    expected_result = [{"ok": True}]
    setattr(client, mock_attr, Mock(return_value=expected_result))

    result = invoke(client)

    assert result == expected_result
    getattr(client, mock_attr).assert_called_once_with(*expected_args, **expected_kwargs)
